### ISSUE TITLE
pre compiled man pages are not installed

### ISSUE THREAD

**Issue by igaw** [linux-nvme/libnvme#184]
The current configuration will only install man pages when they are build from scratch. The pre compiled man pages in the source tree are not considered when installing.

**Comment by igaw** [comment]
Good question. I don't know.

Sure we have: https://github.com/linux-nvme/libnvme/tree/master/doc/man

**Comment by hreinecke** [comment]
Primary reason is that compiling man-pages requires additional tooling, so building the package would be getting ever more complex.
I would vote for regenerating manpage on every release.

**Comment by igaw** [comment]
I agree. In this case we should install them too.

**Comment by hreinecke** [comment]
Please check PR #215 . That should have all what's required here.
