### ISSUE TITLE
doc/meson.build licence 

### ISSUE THREAD

**Issue by igaw** [linux-nvme/libnvme#216]
Hi Martin, 

the doc/meson.build file contains following SPDX license text"

`# SPDX-License-Identifier: BSD-3`

Please send a PR which changes this to 

`# SPDX-License-Identifier: LGPL-2.1-or-later`

Also the descriptionis wrong:

`# This file is part of STorage Appliance Services (STAS).
`

Thanks,
Daniel

**Comment by igaw** [comment]
@martin-belanger

**Comment by martin-belanger** [comment]
Fixed: https://github.com/linux-nvme/libnvme/pull/217
