### ISSUE TITLE
meson -Dman=true doesn't rebuild the man pages

### ISSUE THREAD

**Issue by hreinecke** [linux-nvme/libnvme#218]
Running 'meson -Dman=true' will not regenerated the man pages; primarily because it's running off a separate subdirectory, and any man pages will be stored there (and not in the master directory 'man/doc'). But more importantly, it will just create single 'libnvme.2' file based on the contents of 'doc/libnvme.rst', and not the individual man pages we have now.

And furthermore, the 'libnvme.rst' file is never regenerated based on the contents of the actual source files.

**Comment by igaw** [comment]
In nvme-cli we will only install the documentation when -Ddocs=all, -Ddocs=man or -Ddocs=html is used. First it will try to generated the docs but if the needed tooling is not available it falls back to use the pre compiled ones. I think this scheme makes also sense to implement here. Thoughts?
