### ISSUE TITLE
 python.platlibdir and python.install_env are mutually exclusive

### ISSUE THREAD

**Issue by igaw** [linux-nvme/libnvme#303]
https://github.com/linux-nvme/libnvme/actions/runs/2021673441

**Comment by glimchb** [comment]
let me check

**Comment by glimchb** [comment]
I noticed `python3.8` vs `Python/3.10.2` looking into that

**Comment by glimchb** [comment]
@igaw i have 2 proposal fixes... testing them now

**Comment by igaw** [comment]
Cool thanks. Personally, the first version looks better to my eyes because it depends on less special stuff (e.g. not using pipx (?)).

**Comment by glimchb** [comment]
@igaw found it, the problem was with newly (2days ago) release [meson `0.62` version](https://github.com/mesonbuild/meson/releases/tag/0.62.0)

**Comment by eli-schwartz** [comment]
But why are they both being specified?

**Comment by glimchb** [comment]
@eli-schwartz bug in https://pypi.org/project/mesonpep517/
I opened #271 evaluate switch to https://pypi.org/project/meson-python/

**Comment by eli-schwartz** [comment]
If you are so positive it's a bug in that project, maybe you could answer my question by describing the bug? :)

**Comment by glimchb** [comment]
@eli-schwartz you are right, I didn't investigate that project and didn't see an error in the code
we can keep this issue open but merge the PR to allow CI to pass

**Comment by glimchb** [comment]
fixed by https://github.com/mesonbuild/meson/issues/10181 @igaw you can close

**Comment by igaw** [comment]
Okay, so we just have to wait for the next release of meson to drop the version requirement in pyproject.toml.
