### ISSUE TITLE
how to use libnvme python binds to interaction with nvme device, should i use ioctl to send commands?

### ISSUE THREAD

**Issue by smice-ICE** [linux-nvme/libnvme#385]

**Comment by martin-belanger** [comment]
Have you checked: https://github.com/linux-nvme/libnvme/tree/master/libnvme

**Comment by martin-belanger** [comment]
ioctl is considered a low-level API. The Python bindings only provide high-level APIs such as `connect`, `disconnect`, `discover`. etc. If you need access to other commands, you may need to provide them yourself by submitting a pull-request.

I would not recommend exposing ioctl directly, but rather provide a high-level command. This can be done in https://github.com/linux-nvme/libnvme/blob/master/libnvme/nvme.i. This is a SWIG module used to wrap the C code and generate the Python bindings.
