### ISSUE TITLE
Missing checks for required libraries when building uuid

### ISSUE THREAD

**Issue by MoshiBin** [linux-nvme/libnvme#394]
Meson is able to setup the build env without `libncurses-dev`, `zlib1g-dev` installed, but when trying to build it will emit errors and warnings such as:

```
../subprojects/uuid/text-utils/ul.c: In function ‘init_term_caps’:
../subprojects/uuid/text-utils/ul.c:173:18: warning: implicit declaration of function ‘tigetstr’ [-Wimplicit-function-declaration]
  173 |  tcs->curs_up  = tigetstr("cuu1");
      |                  ^~~~~~~~
```

and

```
../subprojects/uuid/disk-utils/mkfs.cramfs.c:38:10: fatal error: zconf.h: No such file or directory
   38 | #include <zconf.h>
      |          ^~~~~~~~~
```

**Comment by igaw** [comment]
This looks like the subproject configuration for uuid needs to be updated. libnvme is just the consumer. So this bug report is for https://github.com/mesonbuild/wrapdb

**Comment by igaw** [comment]
Fixed the problem by dropping the dependency on libuuid (https://github.com/linux-nvme/libnvme/commit/7aab6de685df525ab9dda6c0d3d1fecab91bc5d2)
