### ISSUE TITLE
Can't build rpm package

### ISSUE THREAD

**Issue by lignumqt** [linux-nvme/libnvme#408]
I'm trying to build an rpm package, but I'm getting an error, what am I doing wrong?
also I would like to know can i build deb package instead rpm?

I run: `make rpm`
> [0/1] Installing files.
Installing subprojects/json-c-0.15/libjson-c.so to /root/libnvme/.build/meson-private/dist-install/usr/lib/x86_64-linux-gnu
Installing subprojects/openssl-1.1.1l/libcrypto.so to /root/libnvme/.build/meson-private/dist-install/usr/lib/x86_64-linux-gnu
Installing subprojects/openssl-1.1.1l/libssl.so to /root/libnvme/.build/meson-private/dist-install/usr/lib/x86_64-linux-gnu
Installing src/libnvme.so.1.0.0 to /root/libnvme/.build/meson-private/dist-install/usr/lib/x86_64-linux-gnu
Installing symlink pointing to libnvme.so.1.0.0 to /root/libnvme/.build/meson-private/dist-install/usr/lib/x86_64-linux-gnu/libnvme.so.1
Installing symlink pointing to libnvme.so.1 to /root/libnvme/.build/meson-private/dist-install/usr/lib/x86_64-linux-gnu/libnvme.so
Installing /root/libnvme/.build/meson-private/dist-build/subprojects/json-c-0.15/json_config.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/arraylist.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/debug.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/json_c_version.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/json_inttypes.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/json_object.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/json_pointer.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/json_tokener.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/json_util.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/linkhash.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/subprojects/json-c-0.15/printbuf.h to /root/libnvme/.build/meson-private/dist-install/usr/include/json-c
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/src/libnvme.h to /root/libnvme/.build/meson-private/dist-install/usr/include
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/src/nvme/fabrics.h to /root/libnvme/.build/meson-private/dist-install/usr/include/nvme
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/src/nvme/filters.h to /root/libnvme/.build/meson-private/dist-install/usr/include/nvme
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/src/nvme/ioctl.h to /root/libnvme/.build/meson-private/dist-install/usr/include/nvme
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/src/nvme/linux.h to /root/libnvme/.build/meson-private/dist-install/usr/include/nvme
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/src/nvme/log.h to /root/libnvme/.build/meson-private/dist-install/usr/include/nvme
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/src/nvme/tree.h to /root/libnvme/.build/meson-private/dist-install/usr/include/nvme
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/src/nvme/types.h to /root/libnvme/.build/meson-private/dist-install/usr/include/nvme
Installing /root/libnvme/.build/meson-private/dist-unpack/libnvme-1.0/src/nvme/util.h to /root/libnvme/.build/meson-private/dist-install/usr/include/nvme
Installing /root/libnvme/.build/meson-private/dist-build/meson-private/json-c.pc to /root/libnvme/.build/meson-private/dist-install/usr/lib/x86_64-linux-gnu/pkgconfig
Installing /root/libnvme/.build/meson-private/dist-build/meson-private/libnvme.pc to /root/libnvme/.build/meson-private/dist-install/usr/lib/x86_64-linux-gnu/pkgconfig
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer
Distribution package /root/libnvme/.build/meson-dist/libnvme-1.0.tar.xz tested
Created /root/libnvme/.build/meson-dist/libnvme-1.0.tar.xz
rpmbuild -ba .build/libnvme.spec
error: File /root/rpmbuild/SOURCES/libnvme-1.0.tar.gz: No such file or directory
Makefile:43: recipe for target 'rpm' failed
make: *** [rpm] Error 1

**Comment by igaw** [comment]
I agree with Martin. The rpm target is there to ease the developer workflow. I don't want to invest time myself to figure out how to get it working. IIRC @sc108-lee is using this. Maybe he has an idea what's going on.

**Comment by sc108-lee** [comment]
@igaw Thanks for pinging me.
I just made some changes to enable it.
check it out PR #414 :)

**Comment by lignumqt** [comment]
> @igaw Thanks for pinging me. I just made some changes to enable it. check it out PR #414 :)

i get another error:

> rpmbuild -ba .build/libnvme.spec --define "_builddir .build" -v
warning: bogus date in %changelog: Fri Jul 04 2022 Steven Seungcheol Lee <sc108.lee@samsung.com>
error: Failed build dependencies:
	gcc is needed by libnvme-1.0-0.x86_64
	libuuid-devel is needed by libnvme-1.0-0.x86_64
Makefile:43: recipe for target 'rpm' failed
make: *** [rpm] Error 1

but in build log I see

> Run-time dependency uuid found: YES 2.31.1

I forgot to say that I'm trying to build it on ubuntu

**Comment by lignumqt** [comment]
> @lignumqt Check it out new commit added on PR :)

I still get an error

> Installing doc/nvme_version.2 to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/share/man/man2
Installing /root/libnvme/src/libnvme.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include
Installing /root/libnvme/src/libnvme-mi.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include
Installing /root/libnvme/src/nvme/api-types.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/src/nvme/fabrics.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/src/nvme/filters.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/src/nvme/ioctl.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/src/nvme/linux.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/src/nvme/log.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/src/nvme/tree.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/src/nvme/types.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/src/nvme/util.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/src/nvme/mi.h to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/include/nvme
Installing /root/libnvme/.build/meson-private/libnvme.pc to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib/x86_64-linux-gnu/pkgconfig
Installing /root/libnvme/.build/meson-private/libnvme-mi.pc to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib/x86_64-linux-gnu/pkgconfig
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
Processing files: libnvme-1.0-0.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64/libnvme.so.*
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.AYShiF
+ umask 022
+ cd .build
+ DOCDIR=/root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/share/doc/libnvme-1.0
+ export LC_ALL=C
+ export DOCDIR
+ /bin/mkdir -p /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/share/doc/libnvme-1.0
+ cp -pr ../COPYING /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/share/doc/libnvme-1.0
+ exit 0


RPM build errors:
    bogus date in %changelog: Fri Jul 04 2022 Steven Seungcheol Lee <sc108.lee@samsung.com>
    File not found: /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64/libnvme.so.*
Makefile:43: recipe for target 'rpm' failed
make: *** [rpm] Error 1

**Comment by igaw** [comment]
@sc108-lee according the tool, your changelog entry has a bogus date :)

**Comment by sc108-lee** [comment]
@igaw Thanks for checking !, I forgot to change Day of the week when I modify date.
I just pushed with force with that fix(and symbolic link installation)

But as I mentioned above, if there is no /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64/libnvme.so.*
That means meson build install failure.

plz check the symlink installing part like below
[1425/1425] Generating doc/nvme_version_man with a custom command (wrapped by meson to capture output)
Installing src/libnvme.so.1.0.0 to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64
Installing symlink pointing to libnvme.so.1.0.0 to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64/libnvme.so.1
Installing symlink pointing to libnvme.so.1 to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64/libnvme.so
Installing src/libnvme.a to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64
Installing src/libnvme-mi.so.1.0.0 to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64
Installing symlink pointing to libnvme-mi.so.1.0.0 to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64/libnvme-mi.so.1
Installing symlink pointing to libnvme-mi.so.1 to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64/libnvme-mi.so
Installing src/libnvme-mi.a to /root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64

**Comment by igaw** [comment]
The logs say meson installs it to `/root/rpmbuild/BUILDROOT/libnvme-1.0-0.x86_64/usr/lib64`. This looks all okay. And on my system this works. Which version of meson are you using? I am using `0.62.2`.

**Comment by igaw** [comment]
So also fairly new and unlikely to be a problem. No idea why the install step is not coping the artifacts to the right location.

**Comment by sc108-lee** [comment]
@igaw nope, you might see my logs to explain to him.
@lignumqt 
your install directoy is different 
/root/libnvme/.build/meson-private/dist-install/usr/lib/x86_64-linux-gnu/libnvme.so.1

/usr/lib/x86_64-linux-gnu/libnvme.so.1
your meson installing you pkgs on there, but rpmbuild manager finding it from /usr/lib64

if you are want to use install directory as yours.
you need to modify yourself of rpm predefined values.


from Makefile
	rpmbuild -ba ${BUILD-DIR}/libnvme.spec --define "_builddir ${BUILD-DIR}" -v

to
	rpmbuild -ba ${BUILD-DIR}/libnvme.spec --define "_builddir ${BUILD-DIR}" --define "_libdir /usr/lib/x86_64-linux-gnu" -v

and if there is similar problem, you need to define other values as well.

**Comment by lignumqt** [comment]
@sc108-lee yes! it has worked for me. I was able to build the rpm package. Thanks !

**Comment by lignumqt** [comment]
this patch will be in branch v1.0 ?

**Comment by sc108-lee** [comment]
@lignumqt nope, that is tag which has been released already.
so It would be on next version of it.

**Comment by igaw** [comment]
Anything left to be done? It looks like we can close this issue, no?

**Comment by igaw** [comment]
No feedback; closing the report.
