### ISSUE TITLE
undefined reference to `le16_to_cpu'

### ISSUE THREAD

**Issue by lignumqt** [linux-nvme/libnvme#411]
I built and installed from source based on the v1.0 branch (I ran `make && make install` ). took a function for tests from the source files, and tried to minimally compile it, for which I received an error. I found where this function is declared, in the file endian.h, I tried to copy it to /usr/include/nvme. and tried to include it to my source file, to which I got an error that the included file 'config.h',inside 'endian.h', could not be found. I tried to remove from the file  'endian.h' line `#include "config.h"`. after that, everything began to gather, but I'm not sure if this is correct

> [Fri Jul 01 13:30:02 @ ~]:> gcc nvme_test.c -o tests -lnvme -DHAVE_LITTLE_ENDIAN
nvme_test.c: In function ‘test_ctrl’:
nvme_test.c:187:26: warning: implicit declaration of function ‘le16_to_cpu’; did you mean ‘le16toh’? [-Wimplicit-function-declaration]
  printf("  vid:%#04x\n", le16_to_cpu(id.vid));
                          ^~~~~~~~~~~
                          le16toh
/tmp/ccjFABYU.o: In function `test_ctrl':
nvme_test.c:(.text+0x1201): undefined reference to `le16_to_cpu'
nvme_test.c:(.text+0x122a): undefined reference to `le16_to_cpu'
/tmp/ccjFABYU.o: In function `test_namespace':
nvme_test.c:(.text+0x21e3): undefined reference to `le16_to_cpu'
collect2: error: ld returned 1 exit status

**Comment by igaw** [comment]
`le16_to_cpu` is from the ccan library (http://ccodearchive.net/). 

The libnvme header files don't have any dependency on ccan. So the dependency on `le16_to_cpu` is from the nvme_test.c file. In this case you should setup ccan for your project, in order to be able to use the function (check 'Use The Code' section on the ccan website).
