### ISSUE TITLE
Allow disconnect of incomplete connections

### ISSUE THREAD

**Issue by martin-belanger** [linux-nvme/libnvme#431]
While running a stress test on Ubuntu 20.04 (kernel 5.8) where I quickly connect/disconnect to controllers while at the same time adding/removing a nvmet target, I occasionally get a partial connection where the subsystem is missing. In other words, the kernel creates a device node (e.g. /dev/nvme7), but it does not create the subsystem under the sysfs (e.g. /sys/class/nvme-subsystem/nvme-subsys0/nvme7). At this point the kernel goes into a retry loop where it periodically tries to reconnect to the target every 10 seconds. This goes on for 10 minutes before the kernel gives up and removes the partial connection.

While in this condition, we cannot use nvme-cli to disconnect because of this error:
```
# nvme disconnect -d nvme7
failed to lookup subsystem for controller nvme7 
Did not find device nvme7: No such device or address
```

However, if we manually run the following command, we can terminate the connection.
```
# echo 1 > /sys/class/nvme/nvme7/delete_controller
```

I tracked the issue to `nvmf_disconnect()` (nvme-cli's `fabrics.c`) where we call libnvme's `nvme_scan_ctrl()` before invoking the `nvme_disconnect_ctrl(c)` method to disconnect the controller. The problem is that `nvme_scan_ctrl()` fails to create the controller object because of the missing subsystem.

I spoke to @hreinecke about this and he suggested that on a disconnect we should relax the checks in libnvme to ensure that `nvme disconnect` works no matter what. In order to do that, we'll need a new libnvme method that nvme-cli can invoke. There are two things we could do. Either create a new `nvme_scan_ctrl_no_subsys()` that skips scanning the subsystem, or create a new `nvme_disconnect_ctrl()` that can take a device name (e.g. `nvme7`) and directly write to the `/sys/class/nvme/nvme7/delete_controller` interface and skip scanning the controller altogether.

I'm not sure what is the best approach and wanted to get people's opinion before I start implementing something.

**Comment by igaw** [comment]
So something like this:
```diff
diff --git a/fabrics.c b/fabrics.c
index 58a7c31d5eca..77d7978b1dc1 100644
--- a/fabrics.c
+++ b/fabrics.c
@@ -948,11 +948,9 @@ int nvmf_disconnect(const char *desc, int argc, char **argv)
        if (ret < 0) {
                fprintf(stderr, "Failed to scan topology: %s\n",
                         nvme_strerror(errno));
-               nvme_free_tree(r);
-               return ret;
        }
 
-       if (cfg.nqn) {
+       if (err == 0 && cfg.nqn) {
                int i = 0;
                char *n = cfg.nqn;
```
