### ISSUE TITLE
C++ Compiler Error on libnvme-mi

### ISSUE THREAD

**Issue by drakedog2008** [linux-nvme/libnvme#466]
The C++ compiler doesn't fully compatible with C99 standard. So it gave the errors: 

1.  
```
/usr/include/nvme/mi.h:790:56: error: invalid conversion from 'int' to 'nvme_mi_config_smbus_freq' [-fpermissive]
```
2. 
```
/usr/include/nvme/mi.h:2227:9: error: designator order for field 'nvme_ns_mgmt_args::nsid' does not match declaration order in 'nvme_ns_mgmt_args'
 2227 |         };
```

**Comment by jk-ozlabs** [comment]
@drakedog2008 thanks for the report, I'll take a look.

**Comment by jk-ozlabs** [comment]
Looks like @drakedog has a PR already: https://github.com/linux-nvme/libnvme/pull/468

**Comment by igaw** [comment]
The fixes are in the tree. Closing bug report.
8fd81cdb88bb ("mi: Fix C++ compiler errors")
