### ISSUE TITLE
uint128 type is not always available

### ISSUE THREAD

**Issue by igaw** [linux-nvme/libnvme#475]
It turns out the uint128 type is not available on all platforms/compiler combinations:

https://build.opensuse.org/package/live_build_log/home:wagi:branches:bsc1201701/nvme-cli/openSUSE_Tumbleweed/i586

```shell
[    0s] Using BUILD_ARCH=i586:i486:i386

[   26s] C compiler for the host machine: cc (gcc 12.2.1 "cc (SUSE Linux) 12.2.1 20220830 [revision e927d1cf141f221c5a32574bde0913307e140984]")
[   26s] C linker for the host machine: cc ld.bfd 2.39.0.20220810-1

[   26s] cc -Invme.p -I. -I.. -Iccan -I../ccan -I/usr/include/uuid -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -fomit-frame-pointer -D_GNU_SOURCE -include config.h -fomit-frame-pointer -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DOPENSSL_LOAD_CONF -MD -MQ nvme.p/nvme-wrap.c.o -MF nvme.p/nvme-wrap.c.o.d -o nvme.p/nvme-wrap.c.o -c ../nvme-wrap.c
[   26s] In file included from ../nvme.h:30,
[   26s]                  from ../nvme-wrap.c:12:
[   26s] ../util/json.h:47:50: error: unknown type name â€˜__uint128_tâ€™; did you mean â€˜__uint32_tâ€™?
[   26s]    47 | struct json_object *util_json_object_new_uint128(__uint128_t val);
[   26s]       |                                                  ^~~~~~~~~~~
[   26s]       |                                                  __uint32_t
```

**Comment by igaw** [comment]
@jk-ozlabs it's not just ARM which hits this bug.

**Comment by jk-ozlabs** [comment]
ah! Good to know, thanks.

**Comment by igaw** [comment]
Will look into it after processing the github backlog.

**Comment by jk-ozlabs** [comment]
Should we just revert those patches introducing `uint128_t` usage? or do we need something more involved instead?

**Comment by igaw** [comment]
Not sure, the thing is a `long double` is 12 bytes on 32bit arch and not 16 bytes long either. So I am pondering if we should introduce our own 16 byte type which maps on uint128_t where it is available and on 32bit something home grown. We don't need any math features such as addition things from this type. It's just reading the value and printing it.

**Comment by jk-ozlabs** [comment]
yeah, I think that `long double` wouldn't suit either, being a floating-point type. I like the idea of a compat type that we have our own print function for.

**Comment by igaw** [comment]
So here is a first dodgy idea how to get it working again but not really fixing it for 32bit.

```c
/* -*- compile-command: "gcc -Wall -std=gnu99 -O0 -g -m32 types.c -o types-32; gcc -Wall -std=gnu99 -O0 -g types.c -o types-64" -*- */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <inttypes.h>

#ifndef __SIZEOF_INT128__
typedef long double __uint128_t;
#endif

typedef unsigned char __u8;

static char __buf[40];

#ifdef __SIZEOF_INT128__

__uint128_t le128_to_cpu(__u8 *data)
{
	__uint128_t result = 0;

	for (int i = 0; i < 16; i++) {
		result *= 256;
		result += data[15 - i];
	}
	return result;
}

char *uint128_t_to_string(__uint128_t val)
{
	uint64_t high = (val >> 64);
	uint64_t low = (uint64_t)val;

	if (high)
		snprintf(__buf, sizeof(__buf), "%" PRIu64 "%" PRIu64, high, low);
	else
		snprintf(__buf, sizeof(__buf), "%" PRIu64, low);

	return __buf;
}

#else

long double le128_to_cpu(__u8 *data)
{
        long double result = 0;

	for (int i = 0; i < 16; i++) {
		result *= 256;
		result += data[15 - i];
	}
	return result;
}

char *uint128_t_to_string(long double val)
{
	snprintf(__buf, sizeof(__buf), "%Lf", val);

	for (int i = strlen(__buf) - 1; i > 0; i--) {
		if (__buf[i] == '.') {
			__buf[i] = '\0';
			break;
		} else if (__buf[i] != '0') {
			__buf[i+1] = '\0';
			break;
		}
	}
	return __buf;
}

#endif

int main(int argc, char *argv[])
{
	uint64_t a = 0;
	long double b = 0;
	__uint128_t c = 0;

	printf("sizeof(uint64_t)    = %zu\n", sizeof(a));
	printf("sizeof(long double) = %zu\n", sizeof(b));
	printf("sizeof(__uint128_t) = %zu\n", sizeof(c));

	__u8 d[8] = { 0, 1, 0, 0, 0, 0, 0, 0 };
	printf("d = %s\n", uint128_t_to_string(le128_to_cpu(d)));

	return a + b + c;
}

```
```

32bit:
sizeof(uint64_t)    = 8
sizeof(long double) = 12
sizeof(__uint128_t) = 12
d = 256

64bit:
sizeof(uint64_t)    = 8
sizeof(long double) = 16
sizeof(__uint128_t) = 16
d = 256

```

**Comment by igaw** [comment]
I would like to keep the 64bit code in place, that means things like

```c
__uint128_t v = le128_to_cpu(some_reg);
printf("%s\n", uint128_t_to_string(v));
```

could be left in place.

**Comment by igaw** [comment]
So here an idea which could work. In case we don't have the `__uint128_t` type, we just define a pointer type and do the conversion magic with buffers. This might work for our usage of the `uint128_t` type. As we just read and print it. There is no other access to it, so we might just get away. It's not a beauty but I really like to avoid to introduce something like `gmp` as it just makes everything complex.

Also I think I would only print those values as hex values. This avoids the necessity handle the overflow calculation for the 10 based system.

```c
typedef __u8* __uint128_t;                                                                         

union __nvme_uint128 {
        unsigned char v[16];
	uint64_t q[2];
};

typedef union __nvme_uint128 __nvme_uint128_t;

__u8 *le128_to_cpu(__u8 *data)
{
	__nvme_uint128_t u;

	memcpy(u.v, data, 16);

	u.q[0] = le64_to_cpu(u.q[0]);
	u.q[1] = le64_to_cpu(u.q[1]);

	memcpy(data, u.v, 16);

	return data;
}

char *uint128_t_to_string(__u8 *val)
{
	__nvme_uint128_t u;

	memcpy(u.v, val, 16);

	if (u.q[1])
		snprintf(__buf, sizeof(__buf), "%" PRIx64 "%" PRIx64, u.q[1], u.q[0]);
	else
		snprintf(__buf, sizeof(__buf), "%" PRIx64, u.q[0]);

	return __buf;
}
```

```
32bit:
sizeof(uint64_t)    = 8
sizeof(long double) = 12
sizeof(__uint128_t) = 4
d = 100

64bit:
sizeof(uint64_t)    = 8
sizeof(long double) = 16
sizeof(__uint128_t) = 16
d = 100
```

**Comment by igaw** [comment]
D'oh the report should have been against nvme-cli not libnvme.

**Comment by igaw** [comment]
@jk-ozlabs can you give this a test and see if it actually works?

**Comment by jk-ozlabs** [comment]
Yep, I like that second option, as it avoids the floating point confusion there. However, I'm not sure about:

```c
typedef __u8* __uint128_t;
```

\- as it should (ideally) be a fixed-size scalar type, and not pointer-size dependent.

We could just keep everything as `__nvme_uint128_t`?

Regardless, will give it a go on 32-bit platforms.

**Comment by igaw** [comment]
As it turns out it was dead simple:

```c
union nvme_uint128 {
        unsigned char v[16];
	uint64_t q[2];
};

typedef union nvme_uint128 nvme_uint128_t;

nvme_uint128_t le128_to_cpu(__u8 *data)
{
	nvme_uint128_t u;

	memcpy(u.v, data, 16);

#if HAVE_BIG_ENDIAN
	u.q[0] = le64_to_cpu(u.q[0]);
	u.q[1] = le64_to_cpu(u.q[1]);
#endif
	return u;
}

char *uint128_to_string(nvme_uint128_t val)
{
	static char buf[40];

	if (val.q[1])
		snprintf(buf, sizeof(buf), "%" PRIx64 "%" PRIx64, val.q[1], val.q[0]);
	else
		snprintf(buf, sizeof(buf), "%" PRIx64, val.q[0]);

	return buf;
}
```

Replaced all `__uint128_t` users with `nvme_uint128_t` all seems to work so far... (famous last words)

**Comment by jk-ozlabs** [comment]
nice!

**Comment by jk-ozlabs** [comment]
OK, this mostly works, except it looks like we want `_to_string` to print in decimal, given the current implementation.

I have a patch in progress - everything else seems to work fine, but we'll need some kind of decimal conversion to keep consistent with the current version.

**Comment by jk-ozlabs** [comment]
PR sent: https://github.com/linux-nvme/nvme-cli/pull/1685

**Comment by igaw** [comment]
> OK, this mostly works, except it looks like we want `_to_string` to print in decimal, given the current implementation.
> 
> I have a patch in progress - everything else seems to work fine, but we'll need some kind of decimal conversion to keep consistent with the current version.

Indeed, I was a bit sloppy with my `printf` attempt. Let's keep it backwards compatible and use your version.

**Comment by igaw** [comment]
Merged everything. Let's see if there are any fallouts from this.
