### ISSUE TITLE
`nvme_get_log_page` ignored `arg->lpo` input parameter

### ISSUE THREAD

**Issue by jinliangw** [linux-nvme/libnvme#541]
Inside the in-band [nvme_get_log_page function](https://github.com/linux-nvme/libnvme/blob/master/src/nvme/ioctl.c#L433), 
the input parameter `arg->lpo` is overwrote accidentally. 
The consequent is that the functions will read log page starting from offset 0, disregarding `arg->lpo` input parameter.

**Comment by jinliangw** [comment]
The issue still exists, but the example is not applied becase  nvme-cli `get-log` subommand doesn't use [nvme_get_log_page function](https://github.com/linux-nvme/libnvme/blob/master/src/nvme/ioctl.c#L433)

**Comment by igaw** [comment]
Okay, let's reopen it for tracking it.

**Comment by igaw** [comment]
https://github.com/linux-nvme/libnvme/pull/547 should address this, right?

**Comment by jinliangw** [comment]
Yes, we can close this issue now.
