### ISSUE TITLE
nvme-list produces error log entry each time (Samsung 950 Pro)

### ISSUE THREAD

**Issue by dswarbrick** [linux-nvme/libnvme#550]
nvme-cli 2.2.x (and possibly earlier 2.x versions) results in an error log entry being created whenever the `nvme list` command is executed, in a system with a Samsung 950 Pro. Version 1.16 did **not** exhibit this.

Drive firmware is 2B0QBXX7 (latest available), and according to smartctl, the supported NVMe version is < 1.2.

The produced error log entries are always the same:
```
# nvme error-log -e 2 /dev/nvme0
Error Log Entries for device:nvme0 entries:2
.................
 Entry[ 0]   
.................
error_count     : 200
sqid            : 0
cmdid           : 0xa00c
status_field    : 0x2002(INVALID_FIELD: A reserved coded value or an unsupported value in a defined field)
phase_tag       : 0
parm_err_loc    : 0
lba             : 0
nsid            : 0x1
vs              : 0
trtype          : The transport type is not indicated or the error is not transport related.
cs              : 0
trtype_spec_info: 0
.................
 Entry[ 1]   
.................
error_count     : 199
sqid            : 0
cmdid           : 0x200a
status_field    : 0x2002(INVALID_FIELD: A reserved coded value or an unsupported value in a defined field)
phase_tag       : 0
parm_err_loc    : 0
lba             : 0
nsid            : 0x1
vs              : 0
trtype          : The transport type is not indicated or the error is not transport related.
cs              : 0
trtype_spec_info: 0
.................
```
Since this system runs a Prometheus node_exporter textfile collector (https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/master/nvme_metrics.sh), which is executed at regular intervals, the `nvme list` command within that script will continually produce error log entries.

Additionally, the kernel log records errors such as these when the nvme-list command is performed:
```
[185931.468688] nvme0: Admin Cmd(0x6), I/O Error (sct 0x0 / sc 0x2) MORE
```
Kernel is 6.0.10.

**Comment by Bacto** [comment]
FYI, I get the same problem with a SAMSUNG PM983 (MZQLB960HAJR-00007) and firmware EDA5702Q.

**Comment by igaw** [comment]
With libnvme v1.7 and the kernel release 6.8 this is fixed.
