### ISSUE TITLE
Question about the judgement( offset & bs ) in function nvme_bytes_to_lba

### ISSUE THREAD

**Issue by Rookie-roob** [linux-nvme/libnvme#616]
I have a doubt in the judgement in function **nvme_bytes_to_lba** .
Relevant code is shown below .

`
if (!count || offset & bs || count & (bs - 1))
`

I have a doubt in the judgement ("offset & bs")  and I wonder if " offset & bs" should be modified to "offset & (bs - 1)"

Thanks for your read.

**Comment by keithbusch** [comment]
Yes, you are correct.

**Comment by igaw** [comment]
I'll prepare a fix... Man I could have spotted that too :D

**Comment by sunyb-dot** [comment]
I also have a question about this function, why are we substracting 1 here?
```
*nlb = (count >> n->lba_shift) - 1;
```

**Comment by keithbusch** [comment]
The subtraction is correct because this value is 'zeroes based". IOW, zero means one. Just an nvme idiosyncracy.
