### ISSUE TITLE
Get LBA Status returns no data

### ISSUE THREAD

**Issue by NateThornton** [linux-nvme/libnvme#753]
The current `nvme_get_lba_status` method never programs the `data_len` field in the passthru command, resulting in no data being returned in the LBAS buffer.

This is an easy enough fix - but there are a couple of solutions and I was hoping one of the maintainers could comment on the preferred one.

1. Add a dedicated `data_len` field to the args, and simply forward that to the passthru field. Allows for the buffer to be sized independently of the mndw field, anything larger than mndw is OK but anything smaller would be an overflow bug. Requires a nvme-cli change.
2. Infer the `data_len` value from the `mndw` value `.data_len = (mndw + 1) << 2`. This is easy and would _not_ require a corresponding nvme-cli change, but if the buffer is any smaller would be an overflow bug.
3. Replace current `mndw` field with `data_len` in the args, and infer mndw from data_len using `__u32 mndw = (args->len >> 2) -1;`. This is the technique used for many other commands: nvme_get_log, nvme_fw_download, nvme_directive_send|recv, and the reservation commands nvme_resv_* . Would require a nvme-cli change but be consistent within the library.

**Comment by igaw** [comment]
Sorry for the late response. The second option seems good enough. We can still add the data_len if needed later. Thanks for the fix!
