### ISSUE TITLE
Doc commit lost 

### ISSUE THREAD

**Issue by martin-gpy** [linux-nvme/libnvme#768]
Looks like the recent json schema doc commit https://github.com/linux-nvme/libnvme/commit/7d1a68f131558042b6812cf84f94e26752b2dfb0 was lost due to the latest doc regenerate commit at https://github.com/linux-nvme/libnvme/commit/f38b1d72e5077c827a3fdf8989dcc2dae70701d1. 

Any idea what happened and how to restore this?

**Comment by igaw** [comment]
The commit https://github.com/linux-nvme/libnvme/commit/7d1a68f131558042b6812cf84f94e26752b2dfb0 updated the auto generated file instead of the source file `config-schema.json.in`. Let me fix this.
