### ISSUE TITLE
Update libnvme Version

### ISSUE THREAD

**Issue by jeff-lien-wdc** [linux-nvme/libnvme#819]
@igaw Do you have plans to update the libnvme (and nvme-cli) versions soon?  The libnvme version was last updated to 1.8 on Feb 14th.  I have one user requesting a specific libnvme fix made after 2/14 and they'd like to load a specific version that they know includes the fix.  Thanks

**Comment by igaw** [comment]
Oh forgot to schedule a release. Sure I'll look into a release next week, would that work?

**Comment by jeff-lien-wdc** [comment]
Yes, thanks Dan.
