### ISSUE TITLE
'SPDX-License-Identifier: LGPL-2.1-or-newer' is not a valid tag

### ISSUE THREAD

**Issue by igaw** [linux-nvme/libnvme#85]
The SPDX-License-Identifier LGPL-2.1-or-newer is not a valid tag in

  https://github.com/linux-nvme/libnvme/blob/95df64a75a175d9ffd4838653f0f61603cca20b0/src/nvme/log.h#L3

I suspect it should be LGPL-2.1-or-later. Hannes could you please send a PR which fixes this? Thanks

**Comment by hreinecke** [comment]
Fixed with PR #120.
