### ISSUE TITLE
Are there any implications if certain checks return 'No' in meson setup?

### ISSUE THREAD

**Issue by bpan2020** [linux-nvme/libnvme#852]
Are there any implications if certain checks return 'No' in meson setup?

$ meson setup .build
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer
[HLL@localhost libnvme-1.9]$ rm -rf .build/
[HLL@localhost libnvme-1.9]$ meson setup .build
The Meson build system
Version: 0.61.5
Source dir: /home/HLL/Jack/tools/nvme/libnvme-1.9
Build dir: /home/HLL/Jack/tools/nvme/libnvme-1.9/.build
Build type: native build
Project name: libnvme
Project version: 1.9
C compiler for the host machine: cc (gcc 11.2.1 "cc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)")
C linker for the host machine: cc ld.bfd 2.36.1-1
Host machine cpu family: x86_64
Host machine cpu: x86_64
C++ compiler for the host machine: c++ (gcc 11.2.1 "c++ (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)")
C++ linker for the host machine: c++ ld.bfd 2.36.1-1
Found pkg-config: /bin/pkg-config (0.28)
Run-time dependency json-c found: YES 0.17.99
Run-time dependency openssl found: YES 1.1.1w
**Header <openssl/opensslv.h> has symbol "LIBRESSL_VERSION_NUMBER" with dependency openssl: NO** 
****Has header "openssl/core_names.h" with dependency openssl: NO**** 
Found CMake: /usr/local/bin/cmake (3.28.3)
Run-time dependency libkeyutils found: NO (tried pkgconfig and cmake)
Checking if "__builtin_type_compatible_p" compiles: YES 
Checking if "typeof" compiles: YES 
Checking if "byteswap.h" compiles: YES 
Checking if "bswap64" : links: YES 
Checking if "statement-expr" compiles: YES 
Checking if "isblank" : links: YES 
Checking if "linux/mctp.h" compiles: YES 
Checking if "netdb" : links: YES 
Checking if "ioctl has glibc-style prototype" compiles: YES 
Compiler for C supports function attribute fallthrough: YES 
Configuring libnvme.spec using configuration
Configuring config.h using configuration
Program python3 found: YES (/bin/python3)
Program swig found: YES (/bin/swig)
**Has header "Python.h" with dependency python: NO** 
Configuring nbft-dump-diff.sh using configuration
Configuring gen-nbft-diffs.sh using configuration
Program diff found: YES (/bin/diff)
Program diff found: YES (/bin/diff)
Program sysfs-tree-diff.sh found: YES (/bin/bash -e /home/HLL/Jack/tools/nvme/libnvme-1.9/test/sysfs/sysfs-tree-diff.sh)
Configuring conf.py using configuration
Configuring api.rst using configuration
Configuring index.rst using configuration
Configuring quickstart.rst using configuration
Configuring installation.rst using configuration
Configuring mi.rst using configuration
Configuring config-schema.json using configuration
Program /home/HLL/Jack/tools/nvme/libnvme-1.9/doc/../scripts/kernel-doc found: YES (/home/HLL/Jack/tools/nvme/libnvme-1.9/doc/../scripts/kernel-doc)
Program /home/HLL/Jack/tools/nvme/libnvme-1.9/doc/../scripts/kernel-doc-check found: YES (/home/HLL/Jack/tools/nvme/libnvme-1.9/doc/../scripts/kernel-doc-check)
Build targets in project: 26

libnvme 1.9

  Paths
    prefixdir     : /usr/local
    sysconfdir    : /usr/local/etc
    bindir        : /usr/local/bin
    includedir    : /usr/local/include
    datadir       : /usr/local/share
    mandir        : /usr/local/share/man
    libdir        : /usr/local/lib64
    build location: /home/HLL/Jack/tools/nvme/libnvme-1.9/.build

  Dependencies
    json-c        : True
    OpenSSL       : True
    keyutitls     : False
    libdbus       : False
    Python 3      : True

Found ninja-1.10.2 at /bin/ninja
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer

**Comment by igaw** [comment]
If a check fails 'no' a feature is not enabled. 

In the highlighted section, meson tries to figure which version of libssl is available. It finds the v1.1.x version but not the v3.x. So you get TLS support via the v1.1.x version.

There is also check for libkeytutils which fails. This means the feature to interact with the kernel keyring is not available.

See the README for more details.
