### ISSUE TITLE
Fix spelling in the documentation and extend it

### ISSUE THREAD

**Issue by igaw** [linux-nvme/libnvme#96]
Fix all spelling errors in documentation.

**Comment by hreinecke** [comment]
Or, indeed, _start_ a documentation by adding 'real' function descriptions instead of the stubs we have now.

**Comment by igaw** [comment]
We had some good progress and updated a lot of the documentation. But it's not finished, though no release blocker. Let's move it to the next planned release.

**Comment by igaw** [comment]
So we have now most of the things documented and fixed all kernel-doc compile warnings. Next step is to run the speller over all header files.
